### PR TITLE
Improve Spanish text in Readme

### PR DESCRIPTION
**Pull request by ccordoba12**
A little improvement for the Spanish speaking community :-)

The current text doesn't sound right to me (but maybe is just me :-)

cc @damianavila

### CODE REVIEW

**Comment by jasongrout** [comment]
Should we also change the exclamation to use that upside down exclamation
point too? I think we should just use regular punctuation instead of emoji
anyway.

**Comment by willingc** [comment]
@jasongrout I'll let @carreau make the decision on emojis, but I think that it was done to add visual appeal to the page similar to the Node.js help repo.

**Comment by Carreau** [comment]
Thanks !

**Comment by damianavila** [comment]
Just for some context... the @ccordoba12 version is more formal whereas my version is more colloquial, I mean day by day usage... and probably inside an Argentinian flavor which is different from the Colombian one... but I am OK with the change :wink:

**Comment by ccordoba12** [comment]
No problem @damianavila :-) When i first read the text, I was like "mmhh, it sounds a bit funny, maybe as a user I'm going to get help by someone who doesn't speak Spanish too well". That prompted me to do the change ;-)

Glad you approve it!

**Pull request merged**
