### PR TITLE
Deprecate this repo

### PR DESCRIPTION
**Pull request by willingc**
@choldgraf @consideRatio fyi for review

### CODE REVIEW

**Review by jasongrout — APPROVED** [review]

**Review by consideRatio — APPROVED** [review]
LGTM thanks Carol for taking action!

**Comment by choldgraf** [comment]
Also looks good to me! Though I don't have permissions to merge :-(  maybe @Carreau does?

**Comment by Carreau** [comment]
Should I archive the repository as well ? It will make everything read only.

**Comment by choldgraf** [comment]
I'm +1 on making it read-only

**Pull request merged**
